drop table if exists cart CASCADE;
drop table if exists category CASCADE;
drop table if exists customer CASCADE;
drop table if exists payment CASCADE;
drop table if exists product CASCADE;
drop table if exists product_cart CASCADE;
create table cart
(
    id          bigint generated by default as identity,
    date        timestamp,
    total       integer not null,
    customer_id bigint,
    payment_id  bigint,
    primary key (id)
);
create table category
(
    id            bigint generated by default as identity,
    category_type varchar(255),
    primary key (id)
);
create table customer
(
    id                      bigint generated by default as identity,
    customer_name           varchar(255),
    country                 varchar(255),
    postal_code             varchar(255),
    city                    varchar(255),
    address                 varchar(255),
    email                   varchar(255),
    telephone_number        varchar(255),
    credit_card_holder      varchar(255),
    credit_card_number      varchar(255),
    credit_card_expiry_date varchar(255),
    primary key (id)
);
create table payment
(
    id             bigint generated by default as identity,
    payment_date   timestamp,
    payment_status varchar(255),
    payment_type   varchar(255),
    primary key (id)
);
create table product
(
    id                  bigint generated by default as identity,
    product_name        varchar(255),
    product_description varchar(255),
    price               integer not null,
    quantity_in_stock   integer not null,
    category_id         bigint,
    primary key (id)
);
create table product_cart
(
    product_id bigint not null,
    cart_id    bigint not null
);
alter table cart
    add constraint fk_customer_id foreign key (customer_id) references customer;
alter table cart
    add constraint fk_payment_id foreign key (payment_id) references payment;
alter table product
    add constraint fk_category_id foreign key (category_id) references category;
alter table product_cart
    add constraint fk_product_cart foreign key (cart_id) references cart;
alter table product_cart
    add constraint fk_cart_product foreign key (product_id) references product