drop table if exists cart CASCADE;
drop table if exists category CASCADE;
drop table if exists customer CASCADE;
drop table if exists payment CASCADE;
drop table if exists product CASCADE;
drop table if exists product_cart CASCADE;
create table cart
(
    id          bigint generated by default as identity,
    total       integer not null,
    customer_id bigint,
    payment_id  bigint,
    primary key (id)
);
create table category
(
    id            bigint generated by default as identity,
    category_type varchar(50),
    primary key (id)
);
create table customer
(
    id            bigint generated by default as identity,
    customer_name varchar(18),
    country       varchar(60),
    postal_code   varchar(10),
    city          varchar(60),
    address       varchar(40),
    email         varchar(40),
    phone         varchar(15),
    primary key (id)
);
create table payment
(
    id             bigint generated by default as identity,
    payment_date   DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_status varchar(50),
    payment_type   varchar(50),
    primary key (id)
);
create table product
(
    id                  bigint generated by default as identity,
    product_name        varchar(50),
    vintage             integer,
    product_description varchar(255),
    price               integer not null,
    quantity_in_stock   integer not null,
    category_id         bigint,
    primary key (id)
);
create table cart_product
(
    product_id bigint not null,
    cart_id    bigint not null
);
alter table cart
    add constraint fk_customer_id foreign key (customer_id) references customer;
alter table cart
    add constraint fk_payment_id foreign key (payment_id) references payment;
alter table product
    add constraint fk_category_id foreign key (category_id) references category;

alter table cart_product
    add constraint fk_product_cart foreign key (cart_id) references cart;
alter table cart_product
    add constraint fk_cart_product foreign key (product_id) references product;