drop table if exists product_cart CASCADE;
create table cart_product (product_id bigint not null, cart_id bigint not null);
alter table cart_product add constraint fk_product_cart foreign key (cart_id) references cart;
alter table cart_product add constraint fk_cart_product foreign key (product_id) references product;
insert into cart_product (product_id, cart_id) values (5, 1);
insert into cart_product (product_id, cart_id) values (10, 1);
insert into cart_product (product_id, cart_id) values (11, 4);
insert into cart_product (product_id, cart_id) values (3, 4);
insert into cart_product (product_id, cart_id) values (9, 3);
insert into cart_product (product_id, cart_id) values (1, 2);
insert into cart_product (product_id, cart_id) values (4, 2);